### PR TITLE
chore:  move antispamdb.sql to carbonio-mta

### PR DESCRIPTION
**Pull request by frisonisland**
See: https://github.com/zextras/carbonio-mta/pull/12

### CODE REVIEW

**Review by keshavbhatt — APPROVED** [review]

**Comment by frisonisland** [comment]
**Note:** noticed zmconfigd files are not mentioned anywhere, should we remove them?

**Comment by frisonisland** [comment]
> > **Note:** noticed zmconfigd files are not mentioned anywhere, should we remove them?
> 
> They are used by carbonio-core PKBUILD if I understand what do you mean (postfix_content_filter.cf, smtpd_relay_restrictions.cf.....)

I just double-checked and these files exist also in mta: https://github.com/zextras/carbonio-mta/tree/devel/zmconfigd
carbonio-build puts them in carbonio-core from mta repo, so I think we can remove them :rocket:

**Review by M0Rf30 — APPROVED** [review]

**Comment by lfasci** [comment]
The antispam SQL script should be tested  or removed I never used It neither in Zimbbra It requires a dedicate mysql instance please open a discussioni anout

**Comment by frisonisland** [comment]
> The antispam SQL script should be tested or removed I never used It neither in Zimbbra It requires a dedicate mysql instance please open a discussioni anout

Sure, we are just moving the file on another repo for now

**Comment by frisonisland** [comment]
> The antispam SQL script should be tested or removed I never used It neither in Zimbbra It requires a dedicate mysql instance please open a discussioni anout

@lfasci , we are still waiting a review from @zextras/mobius to merge . As explained we are just moving files, not discussing about using or not the antispam script and if tested or not, it's out of scope. This is an action that Mobius team can take on its own after these changes are done.

**Comment by lfasci** [comment]
@frisonisland Please:
don't move antispamdb.sql to carbonio-mta
delete dspam.conf.in
and check zmconfigd.log4j.properties that should not be in this repo
Thank you

**Comment by frisonisland** [comment]
> @frisonisland Please: don't move antispamdb.sql to carbonio-mta delete dspam.conf.in and check zmconfigd.log4j.properties that should not be in this repo Thank you

I am afraid it cannot be done, else carbonio-mta PKGBUILD will depend on carbonio-amavis repo and to release it you would have to: make changes here, tag, go to MTA, refer the tag, make changes, merge, bump, tag and finally you will be able to release. That means the release is not standalone.
As I said the new maintainers can move things around however they want after this job is completed. Same about removing log4j properties.

**Comment by frisonisland** [comment]
> @frisonisland Please: don't move antispamdb.sql to carbonio-mta delete dspam.conf.in and check zmconfigd.log4j.properties that should not be in this repo Thank you

@lfasci basically I mean that mta already includes antispamdb.sql (https://github.com/zextras/carbonio-mta/blob/devel/mta/conf/amavisd/mysql/antispamdb.sql) and changes are already merged to make it standalone

**Review by lfasci — APPROVED** [review]
Looks ok to me

**Pull request merged**
